In [69]:
import pandas as pd
df = pd.read_html('BOC_Exchange_Rates.html')[0]

In [70]:
df

   Exchange Rates  \
   Exchange Rates
         Currency
0             AED
1             AUD
2             BHD
3             CAD
4             CHF
5             CNY
6             DKK
7             EUR
8             GBP
9             HKD
10            INR
11            JPY
12            KWD
13            NOK
14            NZD
15            OMR
16            QAR
17            SAR
18            SEK
19            SGD
20            THB
21            USD
22            ZAR

   Exchange Rates:  : currency per unit of foreign currency as at:  29.07.2024 09:00:25 AM  \
                                                                                  Currency
                                                                               Buying Rate
0                                             76.6909
1                                            192.4478
2                                            709.9203
3                                            213.7546
4                                            328.0089
5                                             38.8507
6                                                   -
7                                            320.1805
8                                            381.7867
9                                             36.3197
10                                             3.1204
11                                             1.9116
12                                           900.6568
13                                                  -
14                                           172.1656
15                                           749.0880
16                                            65.1356
17                                            73.3836
18                                                  -
19                                           217.3886
20                                             8.2861
21                                           299.1000
22                                                  -

                                                        \
                Travelers Cheques/ Drafts
   Selling Rate               Buying Rate Selling Rate
0       87.0989                         -            -
1      203.6034                  193.2884     202.7826
2      819.1831                         -            -
3      225.0398                  213.1098     225.0398
4      351.1419                  333.1178     351.1419
5       42.6363                   40.5273      42.6363
6             -                   42.7147      45.2456
7      334.5441                  319.9141     334.6657
8      396.9699                  382.8245     396.5747
9       39.6598                   37.6447      39.6598
10       4.1204                    3.1704       4.0704
11       2.0168                    1.9257       2.0168
12    1021.5651                         -            -
13      28.1859                   26.7472      28.1859
14     183.5984                  172.0109     183.5984
15     806.8226                         -            -
16      85.2185                         -            -
17      86.4126                         -            -
18      28.6847                   27.2386      28.6847
19     230.5264                  219.6575     230.5264
20       9.5161                    8.3061       9.2861
21     307.1000                  298.4000     307.1000
22            -                   16.0675      16.9760


   Telegraphic/PFCA/ BFCA Transfers
                        Buying Rate Selling Rate
0                                 -            -
1                          194.7566     202.7826
2                                 -            -
3                          215.0772     225.0398
4                          336.9773     351.1419
5                           40.8391      42.6363
6                           43.0954      45.2456
7                          322.8445     334.6657
8                          384.5395     396.5747
9                           37.9944      39.6598
10                           3.2204       4.0704
11                           1.9406       2.0168
12                                -            -
13                          26.9651      28.1859
14                         174.0600     183.5984
15                                -            -
16                                -            -
17                                -            -
18                          27.4509      28.6847
19                         221.7912     230.5264
20                           8.3361       9.2861
21                         299.1000     307.1000
22                          16.2094      16.9760

In [71]:
df.head()

  Exchange Rates  \
  Exchange Rates
        Currency
0            AED
1            AUD
2            BHD
3            CAD
4            CHF

  Exchange Rates:  : currency per unit of foreign currency as at:  29.07.2024 09:00:25 AM  \
                                                                                 Currency
                                                                              Buying Rate
0                                            76.6909
1                                           192.4478
2                                           709.9203
3                                           213.7546
4                                           328.0089

                                                       \
               Travelers Cheques/ Drafts
  Selling Rate               Buying Rate Selling Rate
0      87.0989                         -            -
1     203.6034                  193.2884     202.7826
2     819.1831                         -            -
3     225.0398                  213.1098     225.0398
4     351.1419                  333.1178     351.1419


  Telegraphic/PFCA/ BFCA Transfers
                       Buying Rate Selling Rate
0                                -            -
1                         194.7566     202.7826
2                                -            -
3                         215.0772     225.0398
4                         336.9773     351.1419

In [72]:
df.columns = ['_'.join(col).strip() for col in df.columns.values]
df1= df.reset_index()

In [73]:
df1.head(20)

,index,Exchange Rates_Exchange Rates_Currency,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Currency_Buying Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Currency_Selling Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Travelers Cheques/ Drafts_Buying Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Travelers Cheques/ Drafts_Selling Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Telegraphic/PFCA/ BFCA Transfers_Buying Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Telegraphic/PFCA/ BFCA Transfers_Selling Rate
0,0,AED,76.6909,87.0989,-,-,-,-
1,1,AUD,192.4478,203.6034,193.2884,202.7826,194.7566,202.7826
2,2,BHD,709.9203,819.1831,-,-,-,-
3,3,CAD,213.7546,225.0398,213.1098,225.0398,215.0772,225.0398
4,4,CHF,328.0089,351.1419,333.1178,351.1419,336.9773,351.1419
5,5,CNY,38.8507,42.6363,40.5273,42.6363,40.8391,42.6363
6,6,DKK,-,-,42.7147,45.2456,43.0954,45.2456
7,7,EUR,320.1805,334.5441,319.9141,334.6657,322.8445,334.6657
8,8,GBP,381.7867,396.9699,382.8245,396.5747,384.5395,396.5747
9,9,HKD,36.3197,39.6598,37.6447,39.6598,37.9944,39.6598
10,10,INR,3.1204,4.1204,3.1704,4.0704,3.2204,4.0704
11,11,JPY,1.9116,2.0168,1.9257,2.0168,1.9406,2.0168
12,12,KWD,900.6568,1021.5651,-,-,-,-
13,13,NOK,-,28.1859,26.7472,28.1859,26.9651,28.1859
14,14,NZD,172.1656,183.5984,172.0109,183.5984,174.0600,183.5984
15,15,OMR,749.0880,806.8226,-,-,-,-
16,16,QAR,65.1356,85.2185,-,-,-,-
17,17,SAR,73.3836,86.4126,-,-,-,-
18,18,SEK,-,28.6847,27.2386,28.6847,27.4509,28.6847
19,19,SGD,217.3886,230.5264,219.6575,230.5264,221.7912,230.5264

In [74]:
df_dropped = df1.drop(df1.columns[0], axis=1)
df_dropped.head(20)

,Exchange Rates_Exchange Rates_Currency,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Currency_Buying Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Currency_Selling Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Travelers Cheques/ Drafts_Buying Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Travelers Cheques/ Drafts_Selling Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Telegraphic/PFCA/ BFCA Transfers_Buying Rate,Exchange Rates: : currency per unit of foreign currency as at: 29.07.2024 09:00:25 AM_Telegraphic/PFCA/ BFCA Transfers_Selling Rate
0,AED,76.6909,87.0989,-,-,-,-
1,AUD,192.4478,203.6034,193.2884,202.7826,194.7566,202.7826
2,BHD,709.9203,819.1831,-,-,-,-
3,CAD,213.7546,225.0398,213.1098,225.0398,215.0772,225.0398
4,CHF,328.0089,351.1419,333.1178,351.1419,336.9773,351.1419
5,CNY,38.8507,42.6363,40.5273,42.6363,40.8391,42.6363
6,DKK,-,-,42.7147,45.2456,43.0954,45.2456
7,EUR,320.1805,334.5441,319.9141,334.6657,322.8445,334.6657
8,GBP,381.7867,396.9699,382.8245,396.5747,384.5395,396.5747
9,HKD,36.3197,39.6598,37.6447,39.6598,37.9944,39.6598
10,INR,3.1204,4.1204,3.1704,4.0704,3.2204,4.0704
11,JPY,1.9116,2.0168,1.9257,2.0168,1.9406,2.0168
12,KWD,900.6568,1021.5651,-,-,-,-
13,NOK,-,28.1859,26.7472,28.1859,26.9651,28.1859
14,NZD,172.1656,183.5984,172.0109,183.5984,174.0600,183.5984
15,OMR,749.0880,806.8226,-,-,-,-
16,QAR,65.1356,85.2185,-,-,-,-
17,SAR,73.3836,86.4126,-,-,-,-
18,SEK,-,28.6847,27.2386,28.6847,27.4509,28.6847
19,SGD,217.3886,230.5264,219.6575,230.5264,221.7912,230.5264

In [75]:
df_dropped = df1.drop(df1.columns[0], axis=1)
first_column = df_dropped.iloc[:, 0]
print(first_column)

0     AED
1     AUD
2     BHD
3     CAD
4     CHF
5     CNY
6     DKK
7     EUR
8     GBP
9     HKD
10    INR
11    JPY
12    KWD
13    NOK
14    NZD
15    OMR
16    QAR
17    SAR
18    SEK
19    SGD
20    THB
21    USD
22    ZAR
Name: Exchange Rates_Exchange Rates_Currency, dtype: object

In [76]:
df_dropped.columns = ['Currency', 'Currency_Buying_Rate', 'Currency_Selling_Rate','Travelers Cheques/Drafts_Buying_Rate','Travelers Cheques/Drafts_Selling_Rate','Telegraphic/PFCA/BFCA Transfers_Buying_Rate','Telegraphic/PFCA/BFCA Transfers_Selling_Rate']

In [77]:
df_dropped.head(30)

,Currency,Currency_Buying_Rate,Currency_Selling_Rate,Travelers Cheques/Drafts_Buying_Rate,Travelers Cheques/Drafts_Selling_Rate,Telegraphic/PFCA/BFCA Transfers_Buying_Rate,Telegraphic/PFCA/BFCA Transfers_Selling_Rate
0,AED,76.6909,87.0989,-,-,-,-
1,AUD,192.4478,203.6034,193.2884,202.7826,194.7566,202.7826
2,BHD,709.9203,819.1831,-,-,-,-
3,CAD,213.7546,225.0398,213.1098,225.0398,215.0772,225.0398
4,CHF,328.0089,351.1419,333.1178,351.1419,336.9773,351.1419
5,CNY,38.8507,42.6363,40.5273,42.6363,40.8391,42.6363
6,DKK,-,-,42.7147,45.2456,43.0954,45.2456
7,EUR,320.1805,334.5441,319.9141,334.6657,322.8445,334.6657
8,GBP,381.7867,396.9699,382.8245,396.5747,384.5395,396.5747
9,HKD,36.3197,39.6598,37.6447,39.6598,37.9944,39.6598
10,INR,3.1204,4.1204,3.1704,4.0704,3.2204,4.0704
11,JPY,1.9116,2.0168,1.9257,2.0168,1.9406,2.0168
12,KWD,900.6568,1021.5651,-,-,-,-
13,NOK,-,28.1859,26.7472,28.1859,26.9651,28.1859
14,NZD,172.1656,183.5984,172.0109,183.5984,174.0600,183.5984
15,OMR,749.0880,806.8226,-,-,-,-
16,QAR,65.1356,85.2185,-,-,-,-
17,SAR,73.3836,86.4126,-,-,-,-
18,SEK,-,28.6847,27.2386,28.6847,27.4509,28.6847
19,SGD,217.3886,230.5264,219.6575,230.5264,221.7912,230.5264
20,THB,8.2861,9.5161,8.3061,9.2861,8.3361,9.2861
21,USD,299.1000,307.1000,298.4000,307.1000,299.1000,307.1000
22,ZAR,-,-,16.0675,16.9760,16.2094,16.9760

In [78]:
df_dropped = df_dropped.replace('-', 0)
df_dropped.head(24)

,Currency,Currency_Buying_Rate,Currency_Selling_Rate,Travelers Cheques/Drafts_Buying_Rate,Travelers Cheques/Drafts_Selling_Rate,Telegraphic/PFCA/BFCA Transfers_Buying_Rate,Telegraphic/PFCA/BFCA Transfers_Selling_Rate
0,AED,76.6909,87.0989,0,0,0,0
1,AUD,192.4478,203.6034,193.2884,202.7826,194.7566,202.7826
2,BHD,709.9203,819.1831,0,0,0,0
3,CAD,213.7546,225.0398,213.1098,225.0398,215.0772,225.0398
4,CHF,328.0089,351.1419,333.1178,351.1419,336.9773,351.1419
5,CNY,38.8507,42.6363,40.5273,42.6363,40.8391,42.6363
6,DKK,0,0,42.7147,45.2456,43.0954,45.2456
7,EUR,320.1805,334.5441,319.9141,334.6657,322.8445,334.6657
8,GBP,381.7867,396.9699,382.8245,396.5747,384.5395,396.5747
9,HKD,36.3197,39.6598,37.6447,39.6598,37.9944,39.6598
10,INR,3.1204,4.1204,3.1704,4.0704,3.2204,4.0704
11,JPY,1.9116,2.0168,1.9257,2.0168,1.9406,2.0168
12,KWD,900.6568,1021.5651,0,0,0,0
13,NOK,0,28.1859,26.7472,28.1859,26.9651,28.1859
14,NZD,172.1656,183.5984,172.0109,183.5984,174.0600,183.5984
15,OMR,749.0880,806.8226,0,0,0,0
16,QAR,65.1356,85.2185,0,0,0,0
17,SAR,73.3836,86.4126,0,0,0,0
18,SEK,0,28.6847,27.2386,28.6847,27.4509,28.6847
19,SGD,217.3886,230.5264,219.6575,230.5264,221.7912,230.5264
20,THB,8.2861,9.5161,8.3061,9.2861,8.3361,9.2861
21,USD,299.1000,307.1000,298.4000,307.1000,299.1000,307.1000
22,ZAR,0,0,16.0675,16.9760,16.2094,16.9760